### PR TITLE
(fix) Convert Craft image position to CF transforms gravity

### LINKED ISSUE #3: Issue with the gravity parameter not populated correctly
When using the plugin to transform images, the `gravity` parameter expected by Cloudflare is not populated as expected. 

The Cloudflare Image Optimization [documentation](https://developers.cloudflare.com/images/transform-images/transform-via-url/#gravity) requires that the `gravity` parameter is filled with either `auto` or a "side", defined like this:

> A side (`"left"`, `"right"`, `"top"`, `"bottom"`) or coordinates specified on a scale from `0.0` (top or left) to `1.0` (bottom or right), `0.5` being the center. The X and Y coordinates are separated by lowercase `x` in the URL format. For example, `0x1` means left and bottom, `0.5x0.5` is the center, `0.5x0.33` is a point in the top third of the image.

The plugin currently sends the value of `position` from the ImageTransform model to the `gravity` property. It does not work as the value of `position` does not match the requirement expected by Cloudflare. 

Currently, using the plugin, our images transforms requests return: `ERROR 9401: Missing or invalid resizing parameters: gravity keyword is not one of the supported values` 

There needs to be a transformation done so the value of `gravity` is computed from `position` and matches the expected value. 

--- 

For context, we are storing source assets locally and using a Cloudflare Image volume for the transforms only.

### PR DESCRIPTION
**Pull request by f-elix**
Fixes https://github.com/DeuxHuitHuit/craft-cloudflare-images/issues/3

### CODE REVIEW

File: src/imagetransforms/CloudflareImagesTransformer.php [hunk 1]
```diff
@@ -25,7 +25,8 @@ public function generateFlexibleVariant(ImageTransform|CloudflareImagesTransform
             $transform[] = "fit={$imageTransform->mode}";
         }
         if ($imageTransform->position) {
-            $transform[] = "gravity={$imageTransform->position}";
+            $gravity = $this->positionToGravity($imageTransform);
+            $transform[] = "gravity={$gravity}";
```
Comment (nitriques) [inline src/imagetransforms/CloudflareImagesTransformer.php]:
```suggestion
            $transform[] = "gravity={$this->positionToGravity($imageTransform)}";
```

Can you check if this work ? I think it does now....

**Review by nitriques — CHANGES_REQUESTED** [review]

File: src/imagetransforms/CloudflareImagesTransformer.php (hunk 1 above)
Comment (nitriques) [reply src/imagetransforms/CloudflareImagesTransformer.php]: This seems to work 
image

File: src/imagetransforms/CloudflareImagesTransformer.php [hunk 2]
```diff
@@ -51,6 +52,19 @@ public function generateFlexibleVariant(ImageTransform|CloudflareImagesTransform
...
+    public function positionToGravity(ImageTransform $imageTransform)
+    {
+        $positions_map = [
+            'left' => 0,
+            'right' => 1,
+            'top' => 0,
+            'bottom' => 1,
+            'center' => 0.5
+        ];
+        [$x, $y] = explode('-', $imageTransform->position);
```
Comment (nitriques) [inline src/imagetransforms/CloudflareImagesTransformer.php]: We should valide that $x and $y are something

File: src/imagetransforms/CloudflareImagesTransformer.php [hunk 3]
```diff
@@ -51,6 +52,19 @@ public function generateFlexibleVariant(ImageTransform|CloudflareImagesTransform
...
+        return implode('x', [$positions_map[$x], $positions_map[$y]]);
```
Comment (nitriques) [inline src/imagetransforms/CloudflareImagesTransformer.php]:
```suggestion
        return implode('x', [$positions_map[$x] ?? '0', $positions_map[$y] ?? '0']);
```

**Review by nitriques — CHANGES_REQUESTED** [review]

File: src/imagetransforms/CloudflareImagesTransformer.php (hunk 1 above)
Comment (f-elix) [reply src/imagetransforms/CloudflareImagesTransformer.php]: It does on my end too! Will adjust.

File: src/imagetransforms/CloudflareImagesTransformer.php [hunk 4]
```diff
@@ -51,6 +51,21 @@ public function generateFlexibleVariant(ImageTransform|CloudflareImagesTransform
...
+        $positions_map = [
+            'left' => 0,
+            'right' => 1,
+            'top' => 0,
+            'bottom' => 1,
+            'center' => 0.5
+        ];
+        $positions = explode('-', $imageTransform->position);
+        $x = $positions[0] ?? 'center';
+        $y = $positions[1] ?? 'center';
```
Comment (nitriques) [inline src/imagetransforms/CloudflareImagesTransformer.php:65]: php requires you to check for undefined keys in arrays. It will crash if the exploded string does not contains an array.

We could add if (count($positions) == 2) and return an empty string or check for individual keys

**Review by nitriques — CHANGES_REQUESTED** [review]

File: src/imagetransforms/CloudflareImagesTransformer.php (hunk 4 above)
Comment (f-elix) [reply src/imagetransforms/CloudflareImagesTransformer.php:65]: It doesn't seem to crash, but it did crash of I had a wrong key form the map, so I adjusted the code.

You can test it here: 

https://php-play.dev/?c=DwfgDgFmBQ0MYBsCGBnFACAkgWyQcwFMAVAJyQDsUAzAexO3QG9p1X0wBXAIwQEs50AEjA0UvAC68a5ANzQAvrESoMRAinFMWbTj37oqHcnEnT0hcgTLiCAMQQEAHrx4EAakhK8K4gBQ58YjJKWnohXlxCUgpqOmwASnRtVmY2NKFxYNiwgF50AG0AXTl0tl4qdF9BCMDokLiAWgA+ETFTckTU0vTBTJjQ7CL0PIAiPDIANwkATxzGXoheFGbWiSlyIhoAcUmZqpqorIH4+RGS7sVu9HLKgmwwcWmqvvr6eM7kq-QSAnEOEnI6AA5EDzqVLt0fn8AcCAPRA9AAOmu9wQNAAJgRfECADS4jJHOLxOSfRSfXR8ASGYztdiiNbSTY7JBTR7+SJBfpxcIcurZBKfLqlYT09ooAD6uDAwwKnyuQIcVHECJyTXQAAYcXLukCvHgIMrhmqAIxar5sIHiGhgFVqzXa0pArg0cRW7C29Cmh3pIFwAjkGwkD3qxEAVm9xW9Ira6wweScYDRmOxDXx1V5hPoK1F62JUccMujDMo+XVhXQIBAwL9AasoKj00LqzF+WN5cr1f9gfrV0EcBodHRAA0mznpBKpflBI521WQ6GwT1+4OAJqjmPjyVIMBT6azjVhxdpKH-QERRMYrFAxz4qfLkjDnFCe-oleFPNpRRk3rqTR5SwAO7oGoGi+HmvSZgw-4EEBASHFy9BgSSEEIdg2YboCeS+l2VgNDW3bIT8KAcAgf4ZL+zQWFYSA2PYTguA4HheD4zyQXm0AEHAEA0EIREkeIMhAA&v=8.3&f=html

**Review by nitriques — APPROVED** [review]
lgtm
